{% set version = "4.0.0" %}

package:
  name: pywps
  version: {{ version }}

source:
  url: https://github.com/geopython/pywps/archive/{{ version }}.tar.gz
  sha256: ed3ce96310066b2b553e8cab4a5090905c09ba5e9d845381ff8617936898a40d

build:
  number: 1000
  skip: True  # [win or py37]
  # self.async = False is invalid syntax in py37, remove the skip in a future version.
  skip: True  # [py>36]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - owslib
    - jsonschema
    - werkzeug
    - lxml
    - sqlalchemy
    - flufl.enum  # [py27]
    - python-dateutil
test:
  imports:
    - pywps

about:
  home: http://pywps.org/
  license: MIT
  summary: 'PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.'

extra:
  recipe-maintainers:
    - cehbrecht
