{% set version = "4.2.0" %}

package:
  name: pywps
  version: {{ version }}

source:
  url: https://github.com/geopython/pywps/archive/{{ version }}.tar.gz
  sha256: adbc671d4a04cdc960c72167cebe96d2ffd89a5f74e3ccd74c2e26649f41e090

build:
  number: 1000
  # self.async = False is invalid syntax in py37, remove the skip in a future version.
  skip: True  # [win or py>36]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - owslib
    - jsonschema
    - lxml
    - werkzeug
    - sqlalchemy
    - python-dateutil
    - requests
    - jinja2
    - pathlib
    - flufl.enum  # [py27]

test:
  imports:
    - pywps

about:
  home: http://pywps.org/
  license: MIT
  license_file: LICENSE.txt
  summary: 'PyWPS (Python Web Processing Service) is an implementation of the Web processing Service standard from Open Geospatial Consortium.'

extra:
  recipe-maintainers:
    - cehbrecht
