travis:
  secure:
    BINSTAR_TOKEN: CErnTmuOA6cEClogp3as25GdmITjmspyraeARBjvCo/YMPpVnImgV83knV9MdsDpd8LlIUL6imAgMKT/1+tVnmhwg1M43SZK/yE0sGnOS4m8yLSOfa7PK8vZcvmyhL90xp/BhD8N8MTl5uiZKcBcNRtFYsk8Cc9gdT7aXOHGk1Gj0ssk3EQjAlIdfrsVSj+mclAueUBj1oscg85ZVTQznLN8lJWIagpkNbqNx8p7nPqt7HtWvCYYxn0jOu/btnXuwDcwNuNesru273+82CMm+BlQci+gXykNwgfS8lwz1q/9EQ5TLQB0TxcKr5Co4h1DT1f0M4i9UKlF6dyAZr/4Avamx6OdUXTkkF2g5C8E5TTJHNi+s00bsOuawrM328/zL0CjvlXKxpstoaHH20CTagbUvXfNfTj3nvady5OC/H+Mmaeibe++cLfX/4ka/c0eXZ2SCZPqJ5CdNohelgjrtKm8bcrzLQjc3HYY7CmSx4d374qzY759PXfzIWUtaIKmAL0NnSk35botiIGrMH2BA1ezX1KMbmvRBwnBLn6gusuE86etJtgHzJk1nbduQ/DOFdI2Wvof4bCnAfXFrMvTSaPYXUBlnzUfczTOCV6qP9wT93r2DPZwb7VkPbuC25RntvGaIEbHNsLQ/o8FaC+h+xyWXtKe1XRxdsYnbOEcmQg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
