travis:
  secure:
    BINSTAR_TOKEN: wug5lTiQ9Jr4xgecz1WgI2Zs7xM4BzkbNdOkmpd4GNEMtQYbWkpXvv/cG4OIRY7/zFyqbt+cuKL9LKMbiAu4BfhrmHLlKTmHT+S0HYIR8VuSr6j+af/4Is1jweKDE1v5ciU1dE2BR+lAJiMzgGhd3JD/4lJvXvNHmS0W3Crq2BxfMWKsK+a2xJ/dNdeq0rwjAIzFYEFDxR6uCCFbcLcypTkRF2Hq7P0aKUDX9bZ4haBs8sB2OyD8VWt1T5hME6PfseIlhIv9GjsSYCJkWVM/i6wTFEo6xDL1uCexIT+jtsYV5LBZBK2m/NAfr9tuh4GYCYaNc6A2AooBDKGVBo++5BhWxdbT1jMit7JEMfddlAqdVeLrqDZXGIEyEIKHqz5PWIzsWfwFSt322GUaq37y8SU8kkE0ZIQeyNBGjUczv/4XpRwsHz5q+QWpJRtHcSFpg9txdsBAmJ/ryQMQ/jFIMoxQ7tNybD2Lt6nrABQBXA+8JoCZscePsFKSXvXcUhSgQ10E4dunhfCFKmAm5VJRz3T/Wx4WrYqaLIxMoh6slVyvwDyXgugxDI/N3QOYZI+DUvC/JAPuj/GBfWz3QoH/On8TGC0/g4uSqSR7QrdK03MQR97BUsSEj6sH5N4kDeI/s6jeCdAChcJzCxK0BFHKnhK2AsGcpnTMpHq5KSe+Ki0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
